<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etiquetas [
  <!ELEMENT etiquetas (nombre, calle, ciudad, pais, codigo)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT calle (#PCDATA)>
  <!ELEMENT ciudad (#PCDATA)>
  <!ELEMENT pais (#PCDATA)>
  <!ELEMENT codigo (#PCDATA)>
]>
<etiquetas>
  <nombre>Roberto García</nombre>
  <calle>c/ Mayor, 27</calle>
  <ciudad>Coslada</ciudad>
  <pais>España</pais>
  <codigo>39343</codigo>
</etiquetas>